name: lemon_js_workspace
description: Workspace for the QuickJS Flutter packages.
publish_to: none

environment:
  sdk: ^3.12.0

workspace:
  - packages/lemon_js
  - packages/lemon_js_ui
  - packages/lemon_js_ui_video_player
  - packages/quickjs_extensions
  - examples/lemon_js_example
